# Generated by Django 3.2.18 on 2023-04-30 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Techsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(upload_to='Product_images/img')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('OLD', 'OLD')], max_length=100)),
                ('information', models.TextField()),
                ('description', models.TextField()),
                ('stock', models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=200)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Filter_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techsy.filter_price')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techsy.brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techsy.categories')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Techsy.color')),
            ],
        ),
    ]
